# Change these first
owner: marketingfintechos # Your GitHub organization or username, where this repository lives
repo: uptime.fintechos.com # The name of this repository

sites:
  - name: FintechOS
    url: https://fintechos.com
  - name: Inside FintechOS
    url: https://inside.fintechos.com
  - name: DCX360
    url: https://dcx360.io

assignees: # Users to assign downtime issues (optional)
  - marketingfintechos
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime.fintechos.com
  logoUrl: https://fintechos.com/wp-content/uploads/2021/04/fintechos-primary-logo.svg
  name: FintechOS Web Status
  introTitle: "FintechOS Marketing Websites Status Page"
  introMessage: Upptime is the open-source uptime monitor and status page, powered entirely by GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
